export const ASSETS = {
  brand: {
    logo: "/brand/logo.svg",
  },
  illustrations: {
    point: "/illustrations/point.svg",
    deliveryVan: "/illustrations/delivery-van.svg",
    users: "/illustrations/users.svg",
    wallet: "/illustrations/wallet.svg",
    orders: "/illustrations/switch.svg",
    shortUpTrend: "/illustrations/short-up-trend.svg",
    shortDownTrend: "/illustrations/short-down-trend.svg",
    longUpTrend: "/illustrations/long-up-trend.svg",
    longDownTrend: "/illustrations/long-down-trend.svg",
    cardCorner: "/illustrations/card-corner.svg",
    gift: "/illustrations/gift.svg",
    happyCustomer: "/illustrations/happy-customer.svg",
    roses: "/illustrations/roses.svg",
    activeRider: "/illustrations/users.svg",
    riderInTransit: "/illustrations/smart-rider.svg",
    awayRider: "/illustrations/normal-rider.svg",
    offlineRider: "/illustrations/offline-rider.svg",
  },
  integrations: {
    flutterwave: "/integrations/flutterwave.svg",
    paystack: "/integrations/paystack.svg",
    google_maps: "/integrations/google_maps.svg",
    okor: "/integrations/okor.svg",
    placeholder: "/images/placeholder-menu.jpg",
  },
} as const
